"""
4.2_celltype_writeback.py
====================
Read cluster_annotation_results.xlsx generated by 4_celltype.py,
Write the cluster -> cell_type annotation back to MuData and save the annotated data and UMAP plot.
"""

import os
import sys
from pathlib import Path

import pandas as pd
import scanpy as sc
import muon as mu
import anndata as ad

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import colorcet as cc
import matplotlib.colors as mcolors


current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.abspath(os.path.join(current_dir, ".."))

if project_root not in sys.path:
    sys.path.insert(0, project_root)
if current_dir not in sys.path:
    sys.path.insert(0, current_dir)


# ============================================================
# ============================================================
RESULT_BASE_DIR = str(Path(current_dir) / "results_sc" / "sc_multiome")

CLUSTER_BASE_DIR = str(Path(RESULT_BASE_DIR) / 'Clustering results')
FINAL_CLUSTER_ALGO = "ACMWEP"
FINAL_LABELS_PATH = str(Path(CLUSTER_BASE_DIR) / "k_8" / FINAL_CLUSTER_ALGO / "final_labels.csv")  # None means automatically finding the latest final_labels.csv / final_clustering.csv under CLUSTER_BASE_DIR

MUDATA_PATH = str(Path(RESULT_BASE_DIR) / "mdata_qc.h5mu")

OUTPUT_BASE_DIR = str(Path(RESULT_BASE_DIR) / "celltype_annotation")
# os.makedirs(OUTPUT_BASE_DIR, exist_ok=True)
ANNOTATION_RESULT_PATH = str(Path(OUTPUT_BASE_DIR) / "cluster_annotation_results_8.xlsx")

MDATA_WITH_CELLTYPE_PATH = str(Path(RESULT_BASE_DIR) / "mdata_with_celltype.h5mu")

SHOW_PLOTS = False


def make_glasbey_palette(categories):
    k = len(categories)
    glasbey_colors = cc.glasbey[:k]
    return [mcolors.to_hex(color) for color in glasbey_colors]


def show_plot_if_enabled():
    if SHOW_PLOTS:
        plt.show(block=False)
        plt.pause(5)
        plt.close()


def find_annotation_dir():
    result_file = Path(ANNOTATION_RESULT_PATH)
    if not result_file.exists():
        raise FileNotFoundError(f"Annotation result file not found: {result_file}")
    return result_file.parent


def load_clustering_labels():
    if FINAL_LABELS_PATH:
        candidates = [Path(FINAL_LABELS_PATH)]
    else:
        base = Path(CLUSTER_BASE_DIR)
        candidates = []
        candidates.extend(base.glob(f"*/{FINAL_CLUSTER_ALGO}/final_labels.csv"))
        candidates.extend(base.glob("*/final_clustering.csv"))
        candidates = sorted(candidates, key=lambda p: p.stat().st_mtime, reverse=True)

    for path in candidates:
        if not path.exists():
            continue

        df = pd.read_csv(path)
        if "cell_name" in df.columns:
            label_col = "final_label" if "final_label" in df.columns else df.columns[-1]
            df["cell_name"] = df["cell_name"].astype(str).str.strip()
            return df.set_index("cell_name")[label_col].astype(str)

        df = pd.read_csv(path, index_col=0)
        if "cluster" in df.columns:
            return df["cluster"].astype(str)
        if "final_label" in df.columns:
            return df["final_label"].astype(str)
        return df.iloc[:, 0].astype(str)

    raise FileNotFoundError(
        'Cluster label file not found, tried: '
        + (Path(CLUSTER_BASE_DIR).as_posix() if not candidates else " ; ".join(str(p) for p in candidates))
    )


def main():
    print("=" * 70)
    print('4.2 Cell type annotations written back to MuData')
    print("=" * 70)

    output_dir = find_annotation_dir()
    annotation_file = Path(ANNOTATION_RESULT_PATH)

    print(f"Annotation result directory: {output_dir}")
    print(f"Annotation result file: {annotation_file}")

    annotation_results = pd.read_excel(annotation_file)
    renamer = {}
    for _, row in annotation_results.iterrows():
        cluster_id = str(row["cluster"])
        cell_type = row.get("final_cell_type", "Unknown")
        renamer[cluster_id] = cell_type

    print('\nSummary of annotation results:')
    for cluster_id, cell_type in sorted(renamer.items(), key=lambda x: int(x[0])):
        print(f"  Cluster {cluster_id}: {cell_type}")

    file_ext = os.path.splitext(MUDATA_PATH)[1].lower()
    if file_ext == ".h5mu":
        mdata = mu.read_h5mu(MUDATA_PATH)
    elif file_ext == ".h5ad":
        adata = ad.read_h5ad(MUDATA_PATH)
        mdata = mu.MuData({"rna": adata})
    else:
        raise ValueError(f"Unsupported file format: {file_ext}")

    clustering = load_clustering_labels()
    mdata["rna"].obs["clusters"] = (
        mdata["rna"].obs_names.astype(str).str.strip().map(clustering).fillna("Unknown")
    )
    mdata["rna"].obs["clusters"] = mdata["rna"].obs["clusters"].astype(str)
    mdata["rna"].obs["cell_type"] = (
        mdata["rna"].obs["clusters"].map(renamer).fillna("Unknown")
    )

    if "atac" in mdata.mod:
        mdata["atac"].obs["clusters"] = "Unknown"
        common_cells = mdata["atac"].obs_names.intersection(mdata["rna"].obs_names)
        unmatched_atac = mdata["atac"].obs_names.difference(mdata["rna"].obs_names)
        print(f"  - ATAC/RNA common cell number: {len(common_cells)}")
        print(f"  - Number of ATAC cells that did not match RNA: {len(unmatched_atac)}")
        if len(unmatched_atac) > 0:
            preview = unmatched_atac[:10].tolist()
            print(f"  - Examples of unmatched ATAC cells (up to 10): {preview}")
            pd.Series(unmatched_atac, name="atac_cell_id").to_csv(
                output_dir / "unmatched_atac_cells.csv",
                index=False,
            )
            print(f"  - Unmatched ATAC cell list saved: {output_dir / 'unmatched_atac_cells.csv'}")
        if len(common_cells) > 0:
            mdata["atac"].obs.loc[common_cells, "clusters"] = (
                mdata["rna"].obs.loc[common_cells, "clusters"].astype(str).values
            )
        mdata["atac"].obs["clusters"] = mdata["atac"].obs["clusters"].astype(str)
        mdata["atac"].obs["cell_type"] = (
            mdata["atac"].obs["clusters"].map(renamer).fillna("Unknown")
        )

    print('\n Cell type annotation write back completed')
    print(f"  - Number of identified cell types: {mdata['rna'].obs['cell_type'].nunique()} species")
    print('  - Distribution of each cell type:')
    for celltype, count in mdata["rna"].obs["cell_type"].value_counts().head(10).items():
        print(f"    · {celltype}: {count} cells ({count / len(mdata['rna'].obs) * 100:.1f}%)")

    celltype_results = mdata["rna"].obs[["clusters", "cell_type"]].copy()
    celltype_results.index.name = "cell_id"
    celltype_results.to_csv(output_dir / "cell_type_annotation_results.csv")
    print(f"   Cell type annotation results have been saved: {output_dir / 'cell_type_annotation_results.csv'}")

    for mod in ["rna", "atac"]:
        if mod in mdata.mod:
            if "counts" not in mdata[mod].layers:
                mdata[mod].layers["counts"] = mdata[mod].X.copy()
                print(f"  - Added layers['counts'] for {mod.upper()}")
            else:
                print(f"  - {mod.upper()} layers['counts'] already exists and will not be overwritten repeatedly.")

    mdata_output_path = Path(MDATA_WITH_CELLTYPE_PATH)
    mdata_output_path.parent.mkdir(parents=True, exist_ok=True)
    mdata.write_h5mu(mdata_output_path)
    print(f"   Annotated MuData saved: {mdata_output_path}")

    # 4.2 The script is only responsible for writing the clustering annotations back to MuData after quality control and saving mdata_with_celltype.h5mu.
    # Integrated, UMAP plot colored by cell_type generated by 5_network.py after multi-omics integration.
    print('  - RNA/ATAC UMAP plots in 4.2 have been skipped.')
    print("=" * 70)
    print(f"The write-back process is completed and the results are saved to: {mdata_output_path.parent}")
    print("=" * 70)
    return


if __name__ == "__main__":
    main()
